from django.shortcuts import render, redirect
from django.http import HttpResponse
import json
from .forms import TeamForm
from .models import DreamTeam, Answers, Contact, Score

from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from random import randint
from django.views.decorators.csrf import csrf_exempt
#from .getPoke import *

from .forms import ContactForm


def pokemon(request):
    return render(request, 'pokemon/home.html')


@login_required(login_url='login_view')
def pokedex(request):
    return render(request, 'pokemon/pokedex.html')


# Quiz page ----------------------------------------------------------------------------------------
@login_required(login_url='login_view')
@csrf_exempt
def quiz(request):
    score = Score.objects.all()
    context = {'score': score}
    return render(request, 'pokemon/quiz.html', context)

def highscore(request):
    if request.method == 'POST':
        score = request.POST.get('score')
        Score.objects.create(score=score)
        return redirect('quiz')
    else:
        return render(request, 'quiz')



def test(request):
    if request.method == 'GET':
        name = pokelist[randint(0, len(pokelist) - 1)]
        aname = name.lower()
        return HttpResponse(aname)


# End of Quiz page ----------------------------------------------------------------------------------


# Dream Team page -----------------------------------------------------------------------------------
@login_required(login_url='login_view')
def dreamTeam(request):
    teams = DreamTeam.objects.all()
    form = TeamForm()
    context = {'teams': teams, 'form': form}
    return render(request, 'pokemon/dreamTeam.html', context)


def add(request):
    form = TeamForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('dreamTeam')
    return HttpResponse('Invalid Form')


@login_required(login_url='login_view')
def update_team(request, team_id):
    team = DreamTeam.objects.get(pk=team_id)
    form = TeamForm(request.POST or None, instance=team)
    if form.is_valid():
        form.save()
        return redirect('dreamTeam')
    return render(request, 'pokemon/update.html', {'form': form})


@login_required(login_url='login_view')
def delete_team(request, team_id):
    team = DreamTeam.objects.get(pk=team_id)
    if request.method == 'POST':
        team.delete()
        return redirect('dreamTeam')
    return render(request, 'pokemon/delete.html', {'team': team})


# End of Dream Team page -----------------------------------------------------------------------------


# Authentication page --------------------------------------------------------------------------------
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login_view')
    else:
        form = UserCreationForm()
    return render(request, 'pokemon/register.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('pokemon')
    else:
        form = AuthenticationForm()
    return render(request, 'pokemon/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('pokemon')


# End of Authentication page -------------------------------------------------------------------------

@login_required(login_url='login_view')
def contact(request):
    if request.method == 'POST':
        # process the data
        form = ContactForm(request.POST)
        if form.is_valid():
            # form.cleaned_data['first_name']
            form.save()
            return render(request, 'pokemon/thanks.html')
        else:
            form = ContactForm()
            context = {'form': form, 'error': 'The data entered is not valid'}
            return render(request, 'pokemon/contact.html', context)
    else:
        form = ContactForm()
        context = {'form': form}
        return render(request, 'pokemon/contact.html', context)


pokelist = [
    'Bulbasaur',
    'Ivysaur',
    'Venusaur',
    'Charmander',
    'Charmeleon',
    'Charizard',
    'Squirtle',
    'Wartortle',
    'Blastoise',
    'Caterpie',
    'Metapod',
    'Butterfree',
    'Weedle',
    'Kakuna',
    'Beedrill',
    'Pidgey',
    'Pidgeotto',
    'Pidgeot',
    'Rattata',
    'Raticate',
    'Spearow',
    'Fearow',
    'Ekans',
    'Arbok',
    'Pikachu',
    'Raichu',
    'Sandshrew',
    'Sandslash',
    'Nidoran♀',
    'Nidorina',
    'Nidoqueen',
    'Nidoran♂',
    'Nidorino',
    'Nidoking',
    'Clefairy',
    'Clefable',
    'Vulpix',
    'Ninetales',
    'Jigglypuff',
    'Wigglytuff',
    'Zubat',
    'Golbat',
    'Oddish',
    'Gloom',
    'Vileplume',
    'Paras',
    'Parasect',
    'Venonat',
    'Venomoth',
    'Diglett',
    'Dugtrio',
    'Meowth',
    'Persian',
    'Psyduck',
    'Golduck',
    'Mankey',
    'Primeape',
    'Growlithe',
    'Arcanine',
    'Poliwag',
    'Poliwhirl',
    'Poliwrath',
    'Abra',
    'Kadabra',
    'Alakazam',
    'Machop',
    'Machoke',
    'Machamp',
    'Bellsprout',
    'Weepinbell',
    'Victreebel',
    'Tentacool',
    'Tentacruel',
    'Geodude',
    'Graveler',
    'Golem',
    'Ponyta',
    'Rapidash',
    'Slowpoke',
    'Slowbro',
    'Magnemite',
    'Magneton',
    'Farfetch',
    'Doduo',
    'Dodrio',
    'Seel',
    'Dewgong',
    'Grimer',
    'Muk',
    'Shellder',
    'Cloyster',
    'Gastly',
    'Haunter',
    'Gengar',
    'Onix',
    'Drowzee',
    'Hypno',
    'Krabby',
    'Kingler',
    'Voltorb',
    'Electrode',
    'Exeggcute',
    'Exeggutor',
    'Cubone',
    'Marowak',
    'Hitmonlee',
    'Hitmonchan',
    'Lickitung',
    'Koffing',
    'Weezing',
    'Rhyhorn',
    'Rhydon',
    'Chansey',
    'Tangela',
    'Kangaskhan',
    'Horsea',
    'Seadra',
    'Goldeen',
    'Seaking',
    'Staryu',
    'Starmie',
    'Mr. Mime',
    'Scyther',
    'Jynx',
    'Electabuzz',
    'Magmar',
    'Pinsir',
    'Tauros',
    'Magikarp',
    'Gyarados',
    'Lapras',
    'Ditto',
    'Eevee',
    'Vaporeon',
    'Jolteon',
    'Flareon',
    'Porygon',
    'Omanyte',
    'Omastar',
    'Kabuto',
    'Kabutops',
    'Aerodactyl',
    'Snorlax',
    'Articuno',
    'Zapdos',
    'Moltres',
    'Dratini',
    'Dragonair',
    'Dragonite',
    'Mewtwo',
    'Mew',
    'Chikorita',
    'Bayleef',
    'Meganium',
    'Cyndaquil',
    'Quilava',
    'Typhlosion',
    'Totodile',
    'Croconaw',
    'Feraligatr',
    'Sentret',
    'Furret',
    'Hoothoot',
    'Noctowl',
    'Ledyba',
    'Ledian',
    'Spinarak',
    'Ariados',
    'Crobat',
    'Chinchou',
    'Lanturn',
    'Pichu',
    'Cleffa',
    'Igglybuff',
    'Togepi',
    'Togetic',
    'Natu',
    'Xatu',
    'Mareep',
    'Flaaffy',
    'Ampharos',
    'Bellossom',
    'Marill',
    'Azumarill',
    'Sudowoodo',
    'Politoed',
    'Hoppip',
    'Skiploom',
    'Jumpluff',
    'Aipom',
    'Sunkern',
    'Sunflora',
    'Yanma',
    'Wooper',
    'Quagsire',
    'Espeon',
    'Umbreon',
    'Murkrow',
    'Slowking',
    'Misdreavus',
    'Unown',
    'Wobbuffet',
    'Girafarig',
    'Pineco',
    'Forretress',
    'Dunsparce',
    'Gligar',
    'Steelix',
    'Snubbull',
    'Granbull',
    'Qwilfish',
    'Scizor',
    'Shuckle',
    'Heracross',
    'Sneasel',
    'Teddiursa',
    'Ursaring',
    'Slugma',
    'Magcargo',
    'Swinub',
    'Piloswine',
    'Corsola',
    'Remoraid',
    'Octillery',
    'Delibird',
    'Mantine',
    'Skarmory',
    'Houndour',
    'Houndoom',
    'Kingdra',
    'Phanpy',
    'Donphan',
    'Porygon2',
    'Stantler',
    'Smeargle',
    'Tyrogue',
    'Hitmontop',
    'Smoochum',
    'Elekid',
    'Magby',
    'Miltank',
    'Blissey',
    'Raikou',
    'Entei',
    'Suicune',
    'Larvitar',
    'Pupitar',
    'Tyranitar',
    'Lugia',
    'Ho-Oh',
    'Celebi',
    'Treecko',
    'Grovyle',
    'Sceptile',
    'Torchic',
    'Combusken',
    'Blaziken',
    'Mudkip',
    'Marshtomp',
    'Swampert',
    'Poochyena',
    'Mightyena',
    'Zigzagoon',
    'Linoone',
    'Wurmple',
    'Silcoon',
    'Beautifly',
    'Cascoon',
    'Dustox',
    'Lotad',
    'Lombre',
    'Ludicolo',
    'Seedot',
    'Nuzleaf',
    'Shiftry',
    'Taillow',
    'Swellow',
    'Wingull',
    'Pelipper',
    'Ralts',
    'Kirlia',
    'Gardevoir',
    'Surskit',
    'Masquerain',
    'Shroomish',
    'Breloom',
    'Slakoth',
    'Vigoroth',
    'Slaking',
    'Nincada',
    'Ninjask',
    'Shedinja',
    'Whismur',
    'Loudred',
    'Exploud',
    'Makuhita',
    'Hariyama',
    'Azurill',
    'Nosepass',
    'Skitty',
    'Delcatty',
    'Sableye',
    'Mawile',
    'Aron',
    'Lairon',
    'Aggron',
    'Meditite',
    'Medicham',
    'Electrike',
    'Manectric',
    'Plusle',
    'Minun',
    'Volbeat',
    'Illumise',
    'Roselia',
    'Gulpin',
    'Swalot',
    'Carvanha',
    'Sharpedo',
    'Wailmer',
    'Wailord',
    'Numel',
    'Camerupt',
    'Torkoal',
    'Spoink',
    'Grumpig',
    'Spinda',
    'Trapinch',
    'Vibrava',
    'Flygon',
    'Cacnea',
    'Cacturne',
    'Swablu',
    'Altaria',
    'Zangoose',
    'Seviper',
    'Lunatone',
    'Solrock',
    'Barboach',
    'Whiscash',
    'Corphish',
    'Crawdaunt',
    'Baltoy',
    'Claydol',
    'Lileep',
    'Cradily',
    'Anorith',
    'Armaldo',
    'Feebas',
    'Milotic',
    'Castform',
    'Kecleon',
    'Shuppet',
    'Banette',
    'Duskull',
    'Dusclops',
    'Tropius',
    'Chimecho',
    'Absol',
    'Wynaut',
    'Snorunt',
    'Glalie',
    'Spheal',
    'Sealeo',
    'Walrein',
    'Clamperl',
    'Huntail',
    'Gorebyss',
    'Relicanth',
    'Luvdisc',
    'Bagon',
    'Shelgon',
    'Salamence',
    'Beldum',
    'Metang',
    'Metagross',
    'Regirock',
    'Regice',
    'Registeel',
    'Latias',
    'Latios',
    'Kyogre',
    'Groudon',
    'Rayquaza',
    'Jirachi',
    'Deoxys',
    'Turtwig',
    'Grotle',
    'Torterra',
    'Chimchar',
    'Monferno',
    'Infernape',
    'Piplup',
    'Prinplup',
    'Empoleon',
    'Starly',
    'Staravia',
    'Staraptor',
    'Bidoof',
    'Bibarel',
    'Kricketot',
    'Kricketune',
    'Shinx',
    'Luxio',
    'Luxray',
    'Budew',
    'Roserade',
    'Cranidos',
    'Rampardos',
    'Shieldon',
    'Bastiodon',
    'Burmy',
    'Wormadam',
    'Mothim',
    'Combee',
    'Vespiquen',
    'Pachirisu',
    'Buizel',
    'Floatzel',
    'Cherubi',
    'Cherrim',
    'Shellos',
    'Gastrodon',
    'Ambipom',
    'Drifloon',
    'Drifblim',
    'Buneary',
    'Lopunny',
    'Mismagius',
    'Honchkrow',
    'Glameow',
    'Purugly',
    'Chingling',
    'Stunky',
    'Skuntank',
    'Bronzor',
    'Bronzong',
    'Bonsly',
    'Mime Jr.',
    'Happiny',
    'Chatot',
    'Spiritomb',
    'Gible',
    'Gabite',
    'Garchomp',
    'Munchlax',
    'Riolu',
    'Lucario',
    'Hippopotas',
    'Hippowdon',
    'Skorupi',
    'Drapion',
    'Croagunk',
    'Toxicroak',
    'Carnivine',
    'Finneon',
    'Lumineon',
    'Mantyke',
    'Snover',
    'Abomasnow',
    'Weavile',
    'Magnezone',
    'Lickilicky',
    'Rhyperior',
    'Tangrowth',
    'Electivire',
    'Magmortar',
    'Togekiss',
    'Yanmega',
    'Leafeon',
    'Glaceon',
    'Gliscor',
    'Mamoswine',
    'Porygon-Z',
    'Gallade',
    'Probopass',
    'Dusknoir',
    'Froslass',
    'Rotom',
    'Uxie',
    'Mesprit',
    'Azelf',
    'Dialga',
    'Palkia',
    'Heatran',
    'Regigigas',
    'Giratina',
    'Cresselia',
    'Phione',
    'Manaphy',
    'Darkrai',
    'Shaymin',
    'Arceus',
    'Victini',
    'Snivy',
    'Servine',
    'Serperior',
    'Tepig',
    'Pignite',
    'Emboar',
    'Oshawott',
    'Dewott',
    'Samurott',
    'Patrat',
    'Watchog',
    'Lillipup',
    'Herdier',
    'Stoutland',
    'Purrloin',
    'Liepard',
    'Pansage',
    'Simisage',
    'Pansear',
    'Simisear',
    'Panpour',
    'Simipour',
    'Munna',
    'Musharna',
    'Pidove',
    'Tranquill',
    'Unfezant',
    'Blitzle',
    'Zebstrika',
    'Roggenrola',
    'Boldore',
    'Gigalith',
    'Woobat',
    'Swoobat',
    'Drilbur',
    'Excadrill',
    'Audino',
    'Timburr',
    'Gurdurr',
    'Conkeldurr',
    'Tympole',
    'Palpitoad',
    'Seismitoad',
    'Throh',
    'Sawk',
    'Sewaddle',
    'Swadloon',
    'Leavanny',
    'Venipede',
    'Whirlipede',
    'Scolipede',
    'Cottonee',
    'Whimsicott',
    'Petilil',
    'Lilligant',
    'Basculin',
    'Sandile',
    'Krokorok',
    'Krookodile',
    'Darumaka',
    'Darmanitan',
    'Maractus',
    'Dwebble',
    'Crustle',
    'Scraggy',
    'Scrafty',
    'Sigilyph',
    'Yamask',
    'Cofagrigus',
    'Tirtouga',
    'Carracosta',
    'Archen',
    'Archeops',
    'Trubbish',
    'Garbodor',
    'Zorua',
    'Zoroark',
    'Minccino',
    'Cinccino',
    'Gothita',
    'Gothorita',
    'Gothitelle',
    'Solosis',
    'Duosion',
    'Reuniclus',
    'Ducklett',
    'Swanna',
    'Vanillite',
    'Vanillish',
    'Vanilluxe',
    'Deerling',
    'Sawsbuck',
    'Emolga',
    'Karrablast',
    'Escavalier',
    'Foongus',
    'Amoonguss',
    'Frillish',
    'Jellicent',
    'Alomomola',
    'Joltik',
    'Galvantula',
    'Ferroseed',
    'Ferrothorn',
    'Klink',
    'Klang',
    'Klinklang',
    'Tynamo',
    'Eelektrik',
    'Eelektross',
    'Elgyem',
    'Beheeyem',
    'Litwick',
    'Lampent',
    'Chandelure',
    'Axew',
    'Fraxure',
    'Haxorus',
    'Cubchoo',
    'Beartic',
    'Cryogonal',
    'Shelmet',
    'Accelgor',
    'Stunfisk',
    'Mienfoo',
    'Mienshao',
    'Druddigon',
    'Golett',
    'Golurk',
    'Pawniard',
    'Bisharp',
    'Bouffalant',
    'Rufflet',
    'Braviary',
    'Vullaby',
    'Mandibuzz',
    'Heatmor',
    'Durant',
    'Deino',
    'Zweilous',
    'Hydreigon',
    'Larvesta',
    'Volcarona',
    'Cobalion',
    'Terrakion',
    'Virizion',
    'Tornadus',
    'Thundurus',
    'Reshiram',
    'Zekrom',
    'Landorus',
    'Kyurem',
    'Keldeo',
    'Meloetta',
    'Genesect',
    'Chespin',
    'Quilladin',
    'Chesnaught',
    'Fennekin',
    'Braixen',
    'Delphox',
    'Froakie',
    'Frogadier',
    'Greninja',
    'Bunnelby',
    'Diggersby',
    'Fletchling',
    'Fletchinder',
    'Talonflame',
    'Scatterbug',
    'Spewpa',
    'Vivillon',
    'Litleo',
    'Pyroar',
    'Flabébé',
    'Floette',
    'Florges',
    'Skiddo',
    'Gogoat',
    'Pancham',
    'Pangoro',
    'Furfrou',
    'Espurr',
    'Meowstic',
    'Honedge',
    'Doublade',
    'Aegislash',
    'Spritzee',
    'Aromatisse',
    'Swirlix',
    'Slurpuff',
    'Inkay',
    'Malamar',
    'Binacle',
    'Barbaracle',
    'Skrelp',
    'Dragalge',
    'Clauncher',
    'Clawitzer',
    'Helioptile',
    'Heliolisk',
    'Tyrunt',
    'Tyrantrum',
    'Amaura',
    'Aurorus',
    'Sylveon',
    'Hawlucha',
    'Dedenne',
    'Carbink',
    'Goomy',
    'Sliggoo',
    'Goodra',
    'Klefki',
    'Phantump',
    'Trevenant',
    'Pumpkaboo',
    'Gourgeist',
    'Bergmite',
    'Avalugg',
    'Noibat',
    'Noivern',
    'Xerneas',
    'Yveltal',
    'Zygarde',
]