# Generated by Django 3.1.3 on 2020-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_answers_dreamteam_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
