# Generated by Django 3.1.3 on 2020-12-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_auto_20201209_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='highscore',
        ),
    ]
